### ISSUE TITLE
Other ic

### ISSUE THREAD

**Issue by saddys** [Johnlon/integrated-circuit-tester#1]
I see you have your own database with a 74245 as well. The smart ic tester can test only 14/16 pin ic's. So does your program test other components too? How do I add a 74374, for example? Or 74240?

Thanks!

**Comment by Johnlon** [comment]
Hi additional chips is a matter of adding tests to the file ...
https://github.com/Johnlon/integrated-circuit-tester/blob/master/chipsDatabase.h

The file format is explained in the docs if I recall correctly.

If you are thinking of building one you could use a bigger Arduino with
more pins and avoid extenders or I could send you a PCBs if postage isn't
bad.

John

**Comment by Johnlon** [comment]
Sorry you meant this file?
The mychipsdatabase.h
Yeah add a pattern to that file and then add the chip to the  list in here
..

https://github.com/Johnlon/integrated-circuit-tester/blob/017f85d0c72f0dbd39f81e58434bf42291b87a08/modeIdentify.ino

**Comment by Johnlon** [comment]
One of the things I had in mind why I setup the serial terminal was to have
the chip dB in python and just send the tests to the board the same way
exploratory mode works , but I got carried away and wrote the GUI instead
and just left the dB in the Arduino.
Did you look at the hackaday pages as there more detail there and I did
some yt videos on the project.

**Comment by saddys** [comment]
Thanks for answer.

I can add pin and modify sketch for test bigger chip, but i cant understand
how make new table in database.txt for other chip (i need 74240 and 74374).
You can gentle help me? Ty


Il lun 22 mar 2021, 04:37 John Lonergan ***@***.***> ha
scritto:

> One of the things I had in mind why I setup the serial terminal was to have
> the chip dB in python and just send the tests to the board the same way
> exploratory mode works , but I got carried away and wrote the GUI instead
> and just left the dB in the Arduino.
> Did you look at the hackaday pages as there more detail there and I did
> some yt videos on the project.
>

**Comment by Johnlon** [comment]
Forget database.txt - that is a copy of someone else's tests and only to be
updated by copying their latest list.

---

You need to edit ...
https://github.com/Johnlon/integrated-circuit-tester/blob/017f85d0c72f0dbd39f81e58434bf42291b87a08/myChipsDatabase.h

Full instructions on how to understand the format is given here ...

https://github.com/Johnlon/integrated-circuit-tester/tree/017f85d0c72f0dbd39f81e58434bf42291b87a08#step1-understand-the-test-case-specification

Have a go first and I'll review a pull request. It's very simple. Read the
doco and tell me what you don't understand


But I can't test your patterns for you for the 240 as I don't have one, but
I might have the flipflop chip.

Thanks for the interest.

John

**Comment by saddys** [comment]
Are you saying that database.txt is not good?

I understand the pattern code, Thanks for the link. 0/1 is used for input
and H/L/Z are for reading. Theorically with a thrut table of a datasheet I
can made for every chip! But this chip have clock, i have to try and learn
to use the pattern

Ty!

Il lun 22 mar 2021, 13:14 John Lonergan ***@***.***> ha
scritto:

> Forget database.txt - that is a copy of someone else's tests and only to be
> updated by copying their latest list.
>
> ---
>
> You need to edit ...
>
> https://github.com/Johnlon/integrated-circuit-tester/blob/017f85d0c72f0dbd39f81e58434bf42291b87a08/myChipsDatabase.h
>
> Full instructions on how to understand the format is given here ...
>
>
> https://github.com/Johnlon/integrated-circuit-tester/tree/017f85d0c72f0dbd39f81e58434bf42291b87a08#step1-understand-the-test-case-specification
>
> Have a go first and I'll review a pull request. It's very simple. Read the
> doco and tell me what you don't understand
>
>
> But I can't test your patterns for you for the 240 as I don't have one, but
> I might have the flipflop chip.
>
> Thanks for the interest.
>
> John
>

**Comment by Johnlon** [comment]
I am saying that database. Txt is the wrong file to edit.
Instead edit mychipsdatabae.h

If I recall the C is for clock but I haven't looked at it in ages.

**Comment by Johnlon** [comment]
Any luck?

**Comment by Johnlon** [comment]
Stale conversation
